### ISSUE TITLE
PA Review: Shopping Cart

### ISSUE THREAD

**Issue by rkoron007** [rkoron007/AtSea#10]
- [x]  Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds

**Comment by rkoron007** [comment]
My shopping cart should be up and running now! It took forever but I'm finally happy with styling and usability. Let me know if you spot any bugs!

**Comment by rkoron007** [comment]
That is so weird- I've been trying to figure it our- remigrated and reseeded and everything. My cart works totally fine on my local machine.

**Comment by rkoron007** [comment]
Fixed the heroku problem- was a seeding error(this is more a reminder for me) XD

**Comment by xnanodax** [comment]
Great work with the cart! 
It is calculating the total price based the quantity * unit price. 

In case you go back to edit this code, consider one mega checkout button for all the items.
