### ISSUE TITLE
PA Review: Item Reviews

### ISSUE THREAD

**Issue by rkoron007** [rkoron007/AtSea#11]
- [x]  Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds

**Comment by rkoron007** [comment]
Hahahahah totally good point I didn't even think about that- fixed now.

**Comment by xnanodax** [comment]
Looks good :)! If you have the time to refactor, you should have an edit form :)

I would also add some padding in the form so when adding a comment, the text isn't right next to the text form.
![screen shot 2018-04-13 at 2 54 24 pm](https://user-images.githubusercontent.com/20424731/38759396-9b2ab612-3f2a-11e8-9180-b5c193cc8f39.png)
