### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by xnanodax** [rkoron007/AtSea#3]
# Sample State
  - [x] State shape is flat!
  - [x] State's keys are camelCased
  - [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `img_url` key in the state, make sure your database also has a column that contains an `img_url`)
  - [x] Correctly formatted
    - [x] Sample state is rendered with 3 back ticks before and after. This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
      - [x] `entities`
      - [x] `session`
      - [x] `errors` (here or in `ui`)
      - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
    
 # Comments:

**Comment by rkoron007** [comment]
Updated State's keys and removed unnecessary keys.

**Comment by xnanodax** [comment]
In the shopping cart slice of state, what was the reason behind adding a userId key?
- [ ] Will items have an "average" rating? If so, the items slice of state should have that calculated by the average rating in the backend instead of the frontend. 
- [ ] Each item should have a key called `comment_ids` and should be equivalent to the array of ids of comments.

**Comment by rkoron007** [comment]
Good Point! I didn't think about the cart already being pulled up with the user. Updated my state shape. :)

**Comment by xnanodax** [comment]
Awesome!
