### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by xnanodax** [rkoron007/AtSea#5]
# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes]
(https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
  - When deleting a comment from an item, you wont need the item's id, you just need to comment's id.
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
    - NOTE: Oh no! You are just missing one route that doesn't have the correct formatting!

# Comments:

**Comment by xnanodax** [comment]
# Overall
I would either stick with comments OR reviews instead of comments/reviews.

# Backend
How will your users sign up?!
You probably dont need the user's id when returning a shopping cart from the rails server. You can leverage the current_user. That way, people can't look into other people's shopping cart.

**Comment by rkoron007** [comment]
Ohhhh in the MVP it says Comments/Review- I thought it needed both the comment and the review(rating?)?

Fixed other back end routes.

**Comment by xnanodax** [comment]
Awesome!

- [ ] Change `/api/carts` to `/api/cart` since users can only look at their own cart.

**Comment by xnanodax** [comment]
Hm. Would we need another backend route for querying a list of items in the splash page vs a list of items a user owns? I don't think we have that route yet. Thoughts?

**Comment by xnanodax** [comment]
Awesome!
