### ISSUE TITLE
PA Review: User Authentication #1

### ISSUE THREAD

**Issue by rkoron007** [rkoron007/AtSea#8]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Demo User Added
 - [x] Styling
 - [x] Smooth, bug free navigation
 - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
 - [x] Adequate and appropriate seeds

**Comment by xnanodax** [comment]
- [ ] When clicking on `register`, closing the modal, and clicking on `register` again, the modal doesn't pop up anymore. Same issue happens with `sign up`. If I alternate between `sign up` and `register`, this isnt a problem.

**Comment by xnanodax** [comment]
Hm. For some reason, a random url doesn't redirect any more 🤔

**Comment by rkoron007** [comment]
Try it now? It should work.

**Comment by xnanodax** [comment]
Currently the redirect works but the login/signup page no longer loads.

Observation: 
Everytime the redirect works, the login/signup page doesnt work.

**Comment by rkoron007** [comment]
Okay that issue should finally be fixed- let me know if it still isn't working though!

**Comment by xnanodax** [comment]
it works! woohoo!
