### ISSUE TITLE
PA Review: Items

### ISSUE THREAD

**Issue by rkoron007** [rkoron007/AtSea#9]
- [x]  Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds

**Comment by rkoron007** [comment]
I'm still getting some weird routing issues once in a while that will happen the stop for not reason but I'm working on it now. All the pages themselves are functional though. If you run into any weird routing patterns please let me know!

**Comment by rkoron007** [comment]
Just put in all the price formatting- sorry forgot to do before I pushed to heroku!

**Comment by xnanodax** [comment]
Great work!

- [ ] When I am looking at an item that I own on the show page, would you want to add a edit button??

**Comment by rkoron007** [comment]
If you go to the user show page you there is an edit button there for items. And I will totally keep on styling as much as I can!

**Comment by rkoron007** [comment]
Can do! I'll add now.

**Comment by xnanodax** [comment]
Great work :)!!! Love the new edit button.

**Comment by xnanodax** [comment]
I would add more detail content to the page. The core functionality is there. I consider this issue done!
